version: '1.1.{build}'

branches:
  only:
  - master
  - dev
  - appveyor

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2019 Preview

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - git submodule update --init --recursive

before_build:
  - dotnet restore "src/Impostor.sln" -v Minimal

build_script:
  - dotnet build "src/Impostor.Tests/Impostor.Tests.csproj" -c Release
  - dotnet build "src/Impostor.Client/Impostor.Client.Cli/Impostor.Client.Cli.csproj" --no-restore -c Release -f net5.0
  - dotnet build "src/Impostor.Client/Impostor.Client.WinForms/Impostor.Client.WinForms.csproj" /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None
  - dotnet build "src/Impostor.Server/Impostor.Server.csproj" --no-restore -c Release -f net5.0

test:
  assemblies:
    only:
      - 'src\Impostor.Tests\bin\Release\net5.0\Impostor.Tests.dll'
  
only_commits:
  files:
    - appveyor.yml
    - src/**/*
    - .gitmodules
