name: Build

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - '.gitmodules'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - '.gitmodules'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.402
      - name: Install dependencies
        run: dotnet restore ./src
      - name: Build Impostor.Client
        run: msbuild ./src/Impostor.Client/Impostor.Client.csproj /p:Configuration=Release
      - name: Build Impostor.Server
        run: dotnet build --no-restore -c Release -f netcoreapp3.1 ./src/Impostor.Server/Impostor.Server.csproj /p:PublishTrimmed=false
      - name: Test
        run: dotnet test --no-restore -v normal -f netcoreapp3.1 ./src
